# Generated by Django 6.0 on 2025-12-17 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('capacity', models.IntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('deposit_percentage', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('rules', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='venues/')),
                ('gallery', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'venues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='venues.venue')),
            ],
            options={
                'db_table': 'venue_blocked_dates',
            },
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['city', 'is_active'], name='venues_city_c32704_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['owner', 'is_active'], name='venues_owner_i_fafe5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blockeddate',
            unique_together={('venue', 'date')},
        ),
    ]
