# Generated by Django 6.0 on 2025-12-19 09:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'db_table': 'amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VenueAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'venue_amenities',
            },
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venues/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'venue_images',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='blockeddate',
            options={'ordering': ['date']},
        ),
        migrations.RemoveIndex(
            model_name='venue',
            name='venues_owner_i_fafe5c_idx',
        ),
        migrations.AddField(
            model_name='blockeddate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='cancellation_policy',
            field=models.TextField(default='Full refund 7 days before event date'),
        ),
        migrations.AddField(
            model_name='venue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='blockeddate',
            name='reason',
            field=models.CharField(blank=True, default='No reason', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(choices=[('Douala', 'Douala'), ('Yaounde', 'Yaoundé'), ('Bafoussam', 'Bafoussam'), ('Garoua', 'Garoua'), ('Bamenda', 'Bamenda'), ('Limbe', 'Limbe'), ('Kribi', 'Kribi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='venue',
            name='commission_percentage',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='venue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='venue',
            name='deposit_percentage',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='venue',
            name='rules',
            field=models.TextField(blank=True, default='no rule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddIndex(
            model_name='blockeddate',
            index=models.Index(fields=['venue', 'date'], name='blocked_dat_venue_i_eec592_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['price_per_day'], name='venues_price_p_dbe07c_idx'),
        ),
        migrations.AlterModelTable(
            name='blockeddate',
            table='blocked_dates',
        ),
        migrations.AddField(
            model_name='venueamenity',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.amenity'),
        ),
        migrations.AddField(
            model_name='venueamenity',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.venue'),
        ),
        migrations.AddField(
            model_name='venueimage',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='venues.venue'),
        ),
        migrations.RemoveField(
            model_name='venue',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='main_image',
        ),
        migrations.AlterUniqueTogether(
            name='venueamenity',
            unique_together={('venue', 'amenity')},
        ),
    ]
