# Generated by Django 6.0 on 2025-12-19 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_booking_4d53ac_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rejection_reason',
            field=models.TextField(blank=True, default='No reason'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, default='None'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='deposit_paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='full_payment_paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_method',
        ),
    ]
